# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---

Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/edf_network.com/msp
	Policies:
		Readers:
			Type: Signature
			Rule: "OR('OrdererMSP.member')"
		Writers:
			Type: Signature
			Rule: "OR('OrdererMSP.member')"
		Admins:
			Type: Signature
			Rule: "OR('OrdererMSP.admin')"

  - &DeveloperOrg
    Name: DeveloperOrg
    ID: DeveloperMSP
    MSPDir: crypto-config/peerOrganizations/developer.edf_network.com/msp
    AnchorPeers:
      - Host: peer0.developer.edf_network.com
        Port: 7051

  - &TechnicianOrg
    Name: TechnicianOrg
    ID: TechnicianMSP
    MSPDir: crypto-config/peerOrganizations/technician.edf_network.com/msp
    AnchorPeers:
      - Host: peer0.technician.edf_network.com
        Port: 7052

# Define the orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.edf_network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

# Define the consortium and application channel
Consortiums:
  SampleConsortium:
    Organizations:
      - *DeveloperOrg
      - *TechnicianOrg

Channels:
  mychannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *DeveloperOrg
        - *TechnicianOrg
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg

# Define the defaults for applications
ApplicationDefaults:
  Organizations:

# Define the profiles for different use cases
Profiles:
  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *DeveloperOrg
          - *TechnicianOrg
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *DeveloperOrg
        - *TechnicianOrg
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
